services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: ParallelCoordinates-LS
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    #startCommand: gunicorn --chdir src app:server
    #startCommand: gunicorn app:server -b 0.0.0.0:$PORT
    startCommand: gunicorn src.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
